### ISSUE TITLE
`dx serve --example` doesn't watch code changes

### ISSUE THREAD

**Issue by bcorey** [DioxusLabs/dioxus#1591]
**Problem**
`dx serve --example example_file` serves as expected but fails to recompile the file when its contents are changed.

**Steps To Reproduce**
- run `dx create new_project`
- add `examples/example_file.rs` and put a basic dioxus app inside
- run `dx serve --example example_file` and then edit the Rust and RSX code inside `example_file.rs`. Observe that the served page doesn't reflect the changes made.

**Expected behavior**
After running `dx serve --example example_file`, `example_file.rs` should recompile when edited, just like `dx serve`  recompiles `main.rs` when it's edited.

**Environment:**
 - Dioxus version: 0.4
 - Rust version: 1.72.0
 - OS info: Win11/WSL2
 - App platform: web - Brave and Firefox

**Questionnaire**
- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
This should be fixed now. The examples path was missing from the watch path

**Comment by bcorey** [comment]
Thanks for putting in a quick fix - however, I ran `cargo install --git https://github.com/DioxusLabs/dioxus dioxus-cli` to get the newest development version of `dioxus-cli` but I'm still not seeing the code recompile on edit. Only when exiting dx and running `dx serve --example example_file` does it recompile the code and refresh the browser

**Comment by ealmloff** [comment]
What does your `dioxus.toml` look like?

The default `dioxus.toml` just changed: https://github.com/DioxusLabs/dioxus/blob/51f342417a856dc0dfea3701d1488953879f2d73/packages/cli/src/assets/dioxus.toml#L26
```toml
[web.watcher]

index_on_404 = true

watch_path = ["src", "examples"]
```
but if you already have a Dioxus.toml, it will not apply to your project

**Comment by bcorey** [comment]
I added that to my dioxus.toml and it works perfectly now, thank you!
