### ISSUE TITLE
0.5 alpha 2 dioxus_core debug messages visible in app debug output

### ISSUE THREAD

**Issue by jeancf** [DioxusLabs/dioxus#2152]
**Problem**

I just ported my desktop app from 0.4 to 0.5 alpha 2. When running, my log messages are drowned into log messages from dioxus_core

**Steps To Reproduce**

- Include dioxus-logger = "0.4" as dependency in Cargo.toml
- Initialise logger with `dioxus_logger::init(LevelFilter::Debug).expect("failed to init logger");`
- See a lot of log lines starting with `[INFO] dioxus_core::` in the console

**Expected behavior**

Only see the log messages output by my app in the terminal (like with 0.4)

**Environment:**
 - Dioxus version: crates.io 0.5.0-alpha.2
 - Rust version: rustc 1.77.0 stable
 - OS info: Arch Linux
 - App platform: desktop

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by jkelleyrtp** [comment]
This should be fixed thanks to #2157

**Comment by jeancf** [comment]
I have `dioxus = { git="https://github.com/dioxuslabs/dioxus", features = ["desktop"] }` in my Cargo.toml and I have run cargo update but I still see the Dioxus log messages in the log of my app.
Is there something else I should do?

**Comment by jeancf** [comment]
Never mind. I reinstalling dioxus-cli and everything is fine.
