### ISSUE TITLE
DX format eats comments at the end of blocks

### ISSUE THREAD

**Issue by RustGrow** [DioxusLabs/dioxus#3030]
While creating an app, sometimes you have to comment out nested tags to see the difference. When saving Ctrl + S, all commented tags are deleted. You have to save them outside the component and then re-insert them. This behavior is not logical at all during development and is annoying.

https://github.com/user-attachments/assets/1bfa12ee-5e6b-4cfc-acc5-b4e1fffe9acd

**Environment:**
Dioxus version: dioxus 0.6.0-alpha.2 (https://github.com/DioxusLabs/dioxus/commit/d0c9b6712d22e8fced9f0b0ac253e266d73eb3d1) from github 03/10/24
Rust version: rustc 1.81.0 (eeb90cda1 2024-09-04)
OS info: Win11
App platform: web
VSCode 1.93.1 (last for 03/10/24)
Dioxus VSCode Extension v0.5.1

**Comment by ochrons** [comment]
It's not only at the end of a block.

This works fine when formatted
```rust
    rsx! {
        //document::Link { rel: "stylesheet", href: asset!("/public/tailwind.css") }
        div {
            class: "flex flex-col justify-center overflow-hidden py-6 px-2",
            "data-theme": "light",
            div { class: "mx-auto max-w-2xl", Router::<BaseRoute> {} }
        }
    }
 ```

Here the comment will get erased during formatting.
```rust
   rsx! {
        //document::Link { rel: "stylesheet", href: asset!("/public/tailwind.css") }
        
        div {
            class: "flex flex-col justify-center overflow-hidden py-6 px-2",
            "data-theme": "light",
            div { class: "mx-auto max-w-2xl", Router::<BaseRoute> {} }
        }
    }
```
leaving
```rust
    rsx! {
        div {
            class: "flex flex-col justify-center overflow-hidden py-6 px-2",
            "data-theme": "light",
            div { class: "mx-auto max-w-2xl", Router::<BaseRoute> {} }
        }
    }
```

This with version 0.5.1 of the extension and 0.6.0-rc.0 of Dioxus.

**Comment by istudyatuni** [comment]
It also removes comments from inside event handlers

```rs
rsx! {
    button {
        onclick: move |_| {
            let a = Some(5);
            match a {
                Some(a) => {
                    // will be removed
                    println!("test")
                },
                None => (),
            }
        },
    }
}
```

**Comment by flba-eb** [comment]
If you have some (e.g. not yet compiling) code in an event handler which you comment out to test something else first, all the commented code is being removed. This can be very annoying while experimenting and figuring out how things work. A fix would be appreciated very much!

**Comment by pseidemann** [comment]
ran into the same issue with the latest version: https://github.com/DioxusLabs/dioxus/issues/4267

**Comment by jkelleyrtp** [comment]
This should be fixed now!

**Comment by Alexandre-aksenov** [comment]
The issue is still observed in version 0.7.3  of Dioxus .

I am running Visual Studio Code 1.109.2 . Here is full description:

Version: 1.109.2
Commit: 591199df409fbf59b4b52d5ad4ee0470152a9b31
Date: 2026-02-10T20:18:23.520Z
Electron: 39.3.0
ElectronBuildId: 13168319
Chromium: 142.0.7444.265
Node.js: 22.21.1
V8: 14.2.231.22-electron.0
OS: Linux x64 6.8.0-100-generic snap

**Comment by toddobryan** [comment]
Please re-open this issue. It's still doing it in version 0.7.9!

**Comment by ImprovingRigmarole** [comment]
I've still been having this on 0.7.9 as well
