### ISSUE TITLE
AtomState has strange behavior in release build

### ISSUE THREAD

**Issue by SheilaLundin** [DioxusLabs/dioxus#706]
```rust
use dioxus::{
    fermi::{use_atom_state, AtomState},
    prelude::*,
};

fn main() {
    dioxus::desktop::launch(app);
}

#[derive(Default)]
struct Value {
    v: usize,
}

#[derive(Props)]
struct TestProps<'a> {
    id: &'a str,
    value: &'a AtomState<Value>,
}

#[allow(non_snake_case)]
fn Test<'a>(cx: Scope<'a, TestProps<'a>>) -> Element {
    let id = cx.props.id;
    let value = cx.props.value;

    cx.render(rsx! {
        div {
            button {
                onclick: move |_| {value.set(Value {v:1})},
                "{id}"
            }
            label {
                [format_args!("{}", value.v)],
            }
        }
    })
}

static VALUE1: Atom<Value> = |_| Value::default();
static VALUE2: Atom<Value> = |_| Value::default();

fn app(cx: Scope) -> Element {
    let value1 = use_atom_state(&cx, VALUE1);
    let value2 = use_atom_state(&cx, VALUE2);
    rsx!(cx,
        div {
            Test {
                id: "value1",
                value: value1,
            }
            Test {
                id: "value2",
                value: value2,
            }
        }
    )
}
```
rust toolchain is update.
run "cargo run"
![image](https://user-images.githubusercontent.com/20018517/210302089-491201c3-d639-4280-a384-75409225fb0a.png)
run "cargo run --release"
![image](https://user-images.githubusercontent.com/20018517/210302196-6bee3625-6e89-411d-95b9-2c47235532bc.png)

**Comment by Demonthos** [comment]
This seems related to #536 and statics merging with higher opt-levels. The fix merged in that case relies on the TypeId of the atom which would not help here.

#562 Uses a different mechanism to generate unique ids that could solve this issue

**Comment by jkelleyrtp** [comment]
This should be fixed in 0.3 now.

**Comment by addap** [comment]
Unfortunately, the behavior is still reproducible on the following versions of dioxus & fermi
```
dioxus = "0.3.1"
dioxus-desktop = "0.3.0"
fermi = "0.3.0"
```
using the example
```
use dioxus::prelude::*;
use dioxus_router::Router;
use fermi::{use_atom_state, use_init_atom_root, Atom, AtomState};

static VALUE1: Atom<i32> = |_| 0;
static VALUE2: Atom<i32> = |_| 0;

fn app(cx: Scope) -> Element {
    use_init_atom_root(&cx);
    let value1 = use_atom_state(&cx, VALUE1);
    let value2 = use_atom_state(&cx, VALUE2);
    cx.render(rsx! {
            div {
            button {
                onclick: move |_| {value1.set(1)},
                "{value1}"
            }
            button {
                onclick: move |_| {value2.set(1)},
                "{value2}"
            }

            }
    })
}

fn main() {
    dioxus_desktop::launch(app);
}
```

**Comment by AllenDang** [comment]
Same here, the issue still persist on 0.3.2
